db.testdatas.remove();
db.testdatas.insert({ sizeX: 2, sizeY: 1, row: 0, col: 0, gaze: true, wristwatch: false, addcell:false, list: false, title: "this is a title", body: "this is some text"});
db.testdatas.insert({ sizeX: 2, sizeY: 2, row: 0, col: 2, gaze: false, wristwatch: true, addcell:false, list: false, title: "this is a title", body: "this is some text"});
db.testdatas.insert({ sizeX: 1, sizeY: 1, row: 0, col: 4, gaze: false, wristwatch: false, addcell:true, list: false, title: "this is a title", body: "this is some text"});
db.testdatas.insert({ sizeX: 1, sizeY: 1, row: 0, col: 5, gaze: false, wristwatch: false, addcell:false, list: true, title: "this is a title", body: "this is some text"});
db.testdatas.insert({ sizeX: 2, sizeY: 1, row: 1, col: 0, gaze: false, wristwatch: false, addcell:false, list: true, title: "this is a title", body: "this is some text"});
db.testdatas.insert({ sizeX: 1, sizeY: 1, row: 1, col: 4, gaze: false, wristwatch: false, addcell:false, list: true, title: "this is a title", body: "this is some text"});
db.testdatas.insert({ sizeX: 1, sizeY: 2, row: 1, col: 5, gaze: false, wristwatch: false, addcell:false, list: true, title: "this is a title", body: "this is some text"});
db.testdatas.insert({ sizeX: 1, sizeY: 1, row: 2, col: 0, gaze: false, wristwatch: false, addcell:false, list: true, title: "this is a title", body: "this is some text"});
db.testdatas.insert({ sizeX: 2, sizeY: 1, row: 2, col: 1, gaze: false, wristwatch: false, addcell:false, list: true, title: "this is a title", body: "this is some text"});
db.testdatas.insert({ sizeX: 1, sizeY: 1, row: 2, col: 3, gaze: false, wristwatch: false, addcell:false, list: true, title: "this is a title", body: "this is some text"});
db.testdatas.insert({ sizeX: 1, sizeY: 1, row: 2, col: 4, gaze: false, wristwatch: false, addcell:false, list: true, title: "this is a title", body: "this is some text"});
db.testdatas.find();